//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OblivionCharacterManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://etherea.co.uk/projects/ocm/ocminfo.php")]
        public string UpdateCheckUri {
            get {
                return ((string)(this["UpdateCheckUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saves")]
        public string RootSaveDirectory {
            get {
                return ((string)(this["RootSaveDirectory"]));
            }
            set {
                this["RootSaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveCharacterName {
            get {
                return ((string)(this["ActiveCharacterName"]));
            }
            set {
                this["ActiveCharacterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OblivionInstallPath {
            get {
                return ((string)(this["OblivionInstallPath"]));
            }
            set {
                this["OblivionInstallPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OblivionLaunchCommandLine {
            get {
                return ((string)(this["OblivionLaunchCommandLine"]));
            }
            set {
                this["OblivionLaunchCommandLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::OblivionCharacterManager.SaveListSorter SaveListSorter {
            get {
                return ((global::OblivionCharacterManager.SaveListSorter)(this["SaveListSorter"]));
            }
            set {
                this["SaveListSorter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSavesInGroups {
            get {
                return ((bool)(this["ShowSavesInGroups"]));
            }
            set {
                this["ShowSavesInGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdatesOnStartup {
            get {
                return ((bool)(this["CheckUpdatesOnStartup"]));
            }
            set {
                this["CheckUpdatesOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadObseOnOblivionLaunch {
            get {
                return ((bool)(this["LoadObseOnOblivionLaunch"]));
            }
            set {
                this["LoadObseOnOblivionLaunch"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int UpdateTimeout {
            get {
                return ((int)(this["UpdateTimeout"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FormsLibrary.FormSettings FormSettings {
            get {
                return ((global::FormsLibrary.FormSettings)(this["FormSettings"]));
            }
            set {
                this["FormSettings"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Characters.dat")]
        public string CharactersFileName {
            get {
                return ((string)(this["CharactersFileName"]));
            }
        }
    }
}
